final-project/routes/web.php
<?php

use App\Http\Controllers\AnswerController;
use App\Http\Controllers\PdfController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\TopicController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\QuestionController;
use App\Http\Controllers\UserController;
use App\Models\Profile;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/questions');
});

Route::get('/home', function () {
    return view('pages/home');
});

Route::resource('topic', TopicController::class)->except(['show']);

Route::get('/generate-topics-pdf', [PdfController::class, 'generatePdf'])->name('generate_topics_pdf');

Route::resource('questions', QuestionController::class);

Route::group(['prefix' => 'answers'], function () {
    Route::post('/{id}', [AnswerController::class, 'store']);
    Route::get('/{id}/edit', [AnswerController::class, 'edit']);
    Route::put('/{id}', [AnswerController::class, 'update']);
    Route::delete('/{id}', [AnswerController::class, 'destroy'])->name('answers.destroy');
});

Route::resource('users', UserController::class);

Route::middleware(['auth'])->group(function () {
    Route::resource('profile', ProfileController::class)->only(['edit', 'update']);
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

final-project/app/Models/Question.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Question extends Model
{
    use HasFactory;
    protected $table = 'questions';
    protected $fillable = ['content', 'thumbnail', 'topic_id', 'user_id'];

    public function user() {
        return $this->belongsTo(User::class, "user_id");
    }

    public function topic() {
        return $this->belongsTo(Topic::class, "topic_id");
    }

    public function answers() {
        return $this->hasMany(Answer::class, "question_id");
    }
}

final-project/app/Http/Controllers/QuestionController.php
<?php

namespace App\Http\Controllers;

use App\Models\Answer;
use App\Models\Question;
use App\Models\Topic;
use Illuminate\Http\Request;
use App\Models\User;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\File;

class QuestionController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth')->except(['index', 'show']);
    }

    public function index(Request $request)
    {

        $search = $request->input('search');
        if ($search) {
            $questions = Question::where('content', "like", '%' . $search . '%')
            ->paginate(5);
        } else {
            $questions = Question::paginate(5);
        }

        return view('pages.questions.index', compact('questions', 'search'));
    }

    public function create()
    {
        $topics = Topic::all();
        return view('pages.questions.create', ['topics' => $topics]);
    }

    public function store(Request $request)
    {
        $request->validate([
            'content' => 'required',
            'thumbnail' => 'required|image|mimes:jpg,png,jpeg',
            'topic_id' => 'required',
        ]);

        $filethumbnail = time() . '.' . $request->thumbnail->extension();
        $request->thumbnail->move(public_path('image'), $filethumbnail);

        Question::create([
            'content' => $request->content,
            'thumbnail' => $filethumbnail,
            'topic_id' => $request->topic_id,
            'user_id' => Auth::user()->id,
        ]);

        return redirect('/questions');
    }

    public function show($id)
    {
        $question = Question::find($id);

        $answers = Answer::where("question_id", "=", $question->id)->with('user')->get();
        $topic = Topic::where("id", "=", $question->topic_id)->first();

        // dd($answers[0]->user->username);

        return view('pages.questions.detail', ['question' => $question, 'answers' => $answers, 'topic' => $topic]);
    }

    public function edit($id)
    {
        $question = Question::find($id);
        $topics = Topic::get();

        return view('pages.questions.edit', ['question' => $question, 'topics' => $topics]);
    }

    public function update(Request $request, $id)
    {
        $request->validate([
            'content' => 'required',
            'topic_id' => 'required',
        ]);

        $question = Question::find($id);

        // Check if a new thumbnail file is provided
        if ($request->hasFile('thumbnail')) {
            $request->validate([
                'thumbnail' => 'image|mimes:jpg,png,jpeg',
            ]);

            // Delete the old thumbnail file
            $path = 'image/';
            File::delete($path . $question->thumbnail);

            // Upload the new thumbnail file
            $filethumbnail = time() . '.' . $request->file('thumbnail')->extension();
            $request->file('thumbnail')->move(public_path('image'), $filethumbnail);

            // Update the question with the new thumbnail
            $question->thumbnail = $filethumbnail;
        }

        // Update other fields
        $question->content = $request->content;
        $question->topic_id = $request->topic_id;
        $question->user_id = Auth::user()->id;

        // Save the changes
        $question->save();

        toastr()->success('Updated successfully!');

        return redirect('/questions');
    }

    public function destroy($id)
    {
        $question = Question::find($id);

        $path = 'image/';
        File::delete($path . $question->thumbnail);

        $question->answers()->delete();

        $question->delete();

        if ($question instanceof Model) {
            toastr()->success('Deleted successfully!');

            return redirect('/questions');
        }

        toastr()->error('An error has occurred please try again later.');

        return back();

        // return redirect('/questions');
    }
}

final-project/resources/views/pages/questions/create.blade.php
@extends('layout/base')

@section('content')
<div class="container-fluid ">
    <div class="card">
        <div class="card-body">
            <div class="basic-fo rm">
                <form action="/questions" method="POST" enctype="multipart/form-data">
                    @csrf
                    @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                    @endif

                    <div class="form-group">
                        <label for="topic">Topic</label>
                        <select name="topic_id" class="form-control form-control-sm">
                            <option>--Pilih Topic--</option>
                            @foreach ($topics as $item)
                            <option value="{{$item->id}}">{{$item->name}}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="content">Questions</label>
                        <textarea class="form-control" name="content" rows="5" placeholder="Ketikan sesuatu .."></textarea>
                    </div>
                    <div class="form-group">
                        <label for="formFile" class="form-label">File</label>
                        <input class="form-control input-flat rounded" type="file" name="thumbnail">
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

final-project/resources/views/pages/questions/detail.blade.php
@extends('layout.base')

@section('content')
    <div class="container-fluid">
        <div class="card">
            <div class="card-body">
                <div class="mb-3 d-flex">
                    <div class="text-center">
                        <img class="card-img-top rounded img-fluid" src="{{ asset('image/' . $question->thumbnail) }}"
                            alt="img_thumbnail" style="height: 350px;width:min-content;">
                    </div>
                    <div class="ml-5 flex-grow-1">
                        <h3>{{ $question->content }}</h3>
                        <p>Posted by: {{ $question->user->username }}</p>
                        <form action="/answers/{{ $question->id }}" method="post">
                            @csrf

                            <div class="form-group">
                                <label for="content">Answer:</label>
                                <textarea class="form-control rounded" name="content" rows="5" placeholder="Give your answer ..."></textarea>
                            </div>
                            <button type="submit" class="btn btn-primary">Add Answer</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        {{-- Comment Section --}}
        @if ($answers->count() > 0)
            <p style="font-size: 20px; font-weight: 700">All answers ({{ $answers->count() }})</p>
        @endif
        @forelse ($answers as $answer)
            <div class="card">
                <div class="card-body d-flex justify-content-between">
                    <div>
                        <h3>{{ $answer->content }}</h3>
                        <p>Replied by: {{ $answer->user->username }}</p>
                        <p>{{ $answer->created_at->ago() }}</p>
                    </div>
                    @auth
                        @if ($answer->user->id === Auth::user()->id)
                            <div class="d-flex justify-content-end">
                                <div class="btn">
                                    <button type="button" class="btn btn-secondary btn-xs button-none" data-toggle="dropdown"
                                        aria-haspopup="true" aria-expanded="false">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                            fill="currentColor" class="bi bi-three-dots" viewBox="0 0 16 16">
                                            <path
                                                d="M3 9.5a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3m5 0a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3m5 0a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3" />
                                        </svg>
                                    </button>
                                    <div class="dropdown-menu">
                                        <div class="col mb-1">
                                            <a href="/answers/{{ $answer->id }}/edit"
                                                class="btn btn-warning btn-block btn-sm">Edit</a>
                                        </div>
                                        <div class="col">
                                            <button type="button" class="btn btn-danger btn-block btn-sm delete-btn"
                                                data-toggle="modal" data-target="#deleteAnswerModal{{ $answer->id }}">
                                                Delete
                                            </button>
                                        </div>
                                    </div>
                                    <x-modal modalId="deleteAnswerModal{{ $answer->id }}"
                                        aria-labelledby="deleteAnswerModalLabel"
                                        action-route="{{ route('answers.destroy', $answer->id) }}" modal-title="Confirm Delete"
                                        modal-body="Are you sure you want to delete this question?"
                                        button-name="Delete"></x-modal>

                                </div>
                            </div>
                        @endif
                    @endauth
                </div>
            </div>
        @empty
            <div class="card p-4">
                <p style="font-size: 20px" class="text-center pb-0">No answers for this Post</p>
            </div>
        @endforelse
    </div>

    </div>
@endsection

final-project/resources/views/pages/questions/detailBackup.blade.php
@extends('layout.base')

@section('content')
    <div class="container-fluid">
        <div class="card">
            <div class="card-body">
                <div class="d-flex justify-content-between">
                    <h2 class="card-title">Questions</h4>
                </div>
                <div class="form-group">
                    <a href="/questions/create" class="btn btn-primary my-2 px-3">Create</a>
                </div>
                <div class="mb-3">
                    @forelse ($questions as $item)
                        <a>{{$item->topic}}</a>
                        <h4>{{ $item->content }}</h4>
                            <a>{{ $item->thumbnail }}</a>

                        @empty
                            <h3>Tidak ada Pertanyaan</h3>
                    @endforelse
                </div>
            </div>
        </div>
    @endsection

final-project/resources/views/pages/questions/edit.blade.php
@extends('layout/base')

@section('content')
<div class="container-fluid ">
    <div class="card">
        <div class="card-body">
            <div class="basic-fo rm">
                <form action="/questions/{{$question->id}}" method="POST" enctype="multipart/form-data">
                    @csrf
                    @method('put')
                    @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                    @endif

                    <div class="form-group">
                        <label for="topic">Topic</label>
                        <select name="topic_id" class="form-control form-control-sm">
                            <option>--Pilih Topic--</option>
                            @forelse ($topics as $topic)
                            @if ($topic->id === $question->topic_id)
                            <option value="{{$topic->id}}" selected>{{$topic->name}}</option>
                            @else
                            <option value="{{$topic->id}}">{{$topic->name}}</option>
                            @endif
                            @empty
                            <option value="">No Data</option>
                            @endforelse
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="content">Questions</label>
                        <textarea class="form-control" name="content" rows="5" placeholder="Ketikan sesuatu ..">{{$question->content}}</textarea>
                    </div>
                    <div class="form-group">
                        <label for="formFile" class="form-label">File</label>
                        <input class="form-control input-flat rounded" type="file" name="thumbnail">
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

final-project/resources/views/pages/questions/index.blade.php
@extends('layout.base')

@section('content')
    <div class="container-fluid">
        <div class="card">
            <div class="card-body">
                <div class="basic-form">
                    <div class="form-group">
                        <h1>What do you want to post or share?</h1>
                    </div>
                    <a href="/questions/create" type="submit" class="btn btn-primary"><i
                            class="fa fa-pencil color-muted"></i><span class="ml-3">Post</span></a>
                </div>
            </div>
        </div>

        @if ($search)
            <p class="mb-4" style="font-size: 24px; font-weight: 700">Result for: {{ $search }}</p>
        @endif
        <div class="row mx-2">
            @forelse ($questions as $question)
                <div class="col-md-6 col-lg-4">
                    <div class="card p-2">
                        <div class="text-center">
                            <img class="card-img-top rounded img-fluid" src="{{ asset('image/' . $question->thumbnail) }}"
                                alt="{{ $question->title }}" style="height: 350px;width:min-content;">
                        </div>
                        <div class="card-body p-2 mt-1">
                            <span class="badge badge-info p-1 mb-2">{{ $question->topic->name }}</span>
                            <h2 class="card-text ">{{ $question->content }}</h2>
                            <div class="d-flex justify-content-between align-items-center">
                                <p>Posted by: {{ $question->user->username }}</p>
                                <p>{{ $question->created_at->ago() }}</p>
                            </div>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="d-flex align-items-center">
                                    <a href="/answers/create" class="pe-auto" style="cursor: pointer;" data-toggle="tooltip"
                                        data-placement="top" title="Reply this post">
                                        <div>
                                            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20"
                                                fill="currentColor" class="bi bi-chat" viewBox="0 0 16 16">
                                                <path
                                                    d="M2.678 11.894a1 1 0 0 1 .287.801 11 11 0 0 1-.398 2c1.395-.323 2.247-.697 2.634-.893a1 1 0 0 1 .71-.074A8 8 0 0 0 8 14c3.996 0 7-2.807 7-6s-3.004-6-7-6-7 2.808-7 6c0 1.468.617 2.83 1.678 3.894m-.493 3.905a22 22 0 0 1-.713.129c-.2.032-.352-.176-.273-.362a10 10 0 0 0 .244-.637l.003-.01c.248-.72.45-1.548.524-2.319C.743 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7-3.582 7-8 7a9 9 0 0 1-2.347-.306c-.52.263-1.639.742-3.468 1.105" />
                                            </svg>
                                        </div>
                                    </a>
                                    <a href="/questions/{{ $question->id }}">
                                        <span class="ml-2">{{ $question->answers->count() }} answers</span>
                                    </a>
                                </div>
                                @auth
                                    @if ($question->user_id === Auth::user()->id)
                                        <div class="d-flex justify-content-end align-items-center">
                                            <div>
                                                <button type="button" class="btn btn-secondary btn-xs button-none" data-toggle="dropdown"
                                                    aria-haspopup="true" aria-expanded="false">
                                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                                        fill="currentColor" class="bi bi-three-dots" viewBox="0 0 16 16">
                                                        <path
                                                            d="M3 9.5a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3m5 0a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3m5 0a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3" />
                                                    </svg>
                                                </button>
                                                <div class="dropdown-menu">
                                                    <div class="col mb-1">
                                                        <a href="/questions/{{ $question->id }}/edit"
                                                            class="btn btn-warning btn-block btn-sm">Edit</a>
                                                    </div>
                                                    <div class="col">
                                                        <button type="button"
                                                            class="btn btn-danger btn-block btn-sm delete-btn"
                                                            data-toggle="modal" data-target="#deleteModal{{ $question->id }}">
                                                            Delete
                                                        </button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <x-modal modalId="deleteModal{{ $question->id }}" aria-labelledby="deleteModalLabel"
                                            action-route="{{ route('questions.destroy', $question->id) }}"
                                            modal-title="Confirm Delete"
                                            modal-body="Are you sure you want to delete this question?"
                                            button-name="Delete"></x-modal>
                                    @endif
                                @endauth
                            </div>
                        </div>
                    </div>
                </div>
            @empty
                @if ($search)
                    <p style="font-size: 18px">Cannot found search with value '{{ $search }}'</p>
                @else
                    <p style="font-size: 18px">No question available</p>
                @endif
            @endforelse
        </div>
        @if (count($questions) > 0)
            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    <li class="page-item {{ $questions->currentPage() == 1 ? 'disabled' : '' }}">
                        <a class="page-link" href="{{ $questions->previousPageUrl() }}" tabindex="-1">Previous</a>
                    </li>
                    @for ($i = 1; $i <= $questions->lastPage(); $i++)
                        <li class="page-item {{ $questions->currentPage() == $i ? 'active' : '' }}">
                            <a class="page-link" href="{{ $questions->url($i) }}">{{ $i }}</a>
                        </li>
                    @endfor
                    <li class="page-item {{ $questions->currentPage() == $questions->lastPage() ? 'disabled' : '' }}">
                        <a class="page-link" href="{{ $questions->nextPageUrl() }}">Next</a>
                    </li>
                </ul>
            </nav>
        @endif
    </div>
@endsection